"""
Exposes a URL that specifies the behaviour of this scalar.
"""
directive @specifiedBy(
  """
  The URL that specifies the behaviour of this scalar.
  """
  url: String!
) on SCALAR

enum LoggerType {
  CARTASENSE
  SKYCELL_SAVY_BLE
}

enum Position {
  TOP
  BOTTOM
  LEFT
  RIGHT
  AMBIENT
  INTERNAL
  BACK
}

type Query {
  sensorDataContainer(
    serialNumber: String!
    position: [Position]!
    from: String!
    to: String!
    loggerType: LoggerType!
  ): SensorDataResponse
}

type SensorDataItem {
  d: [Float]
  t: String
}

type SensorDataResponse {
  loggerTypes: [LoggerType]
  sensorCodes: [String]
  sensorData: [SensorDataItem]
  sensorLabels: [String]
}
