name: PULL_REQUEST_CHECK

on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: bahmutov/npm-install@v1
      - name: Check version
        run: node checkVersion.js
      - name: Lint
        run: npm run lint
      - name: Unit testing
        run: npm run test
      - name: Try to build
        run: |
          npm run compile
          npm run build-storybook
      - name: SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_SHA: ${{ github.event.after }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
